/**
 * The Worker's bindings, as declared per environment in wrangler.jsonc.
 *
 * Runtime types (D1Database, Ai, ...) come from worker-configuration.d.ts, generated by
 * `npm run types`. This interface is written by hand rather than generated: the top-level
 * wrangler config only has DB (local/test), but every deployed environment has all of these.
 */
export interface Env {
  DB: D1Database;
  /**
   * Vectorize index (`wts-chunks-<env>`). Typed `Vectorize`, the current (v2) binding, which
   * has metadata filtering and async mutations. `VectorizeIndex` is the deprecated beta type.
   */
  VEC: Vectorize;
  AI: Ai;
  /**
   * Analytics Engine (analytics.ts). Optional: a deploy once failed with code 10089 while it
   * was declared (Checkpoint F), and a missing or failing analytics write must never break a
   * request.
   */
  ANALYTICS?: AnalyticsEngineDataset;
  /**
   * Seconds to cache search responses at the edge (a var in wrangler.jsonc, "3600" in each
   * deployed environment). Unset or not a positive integer: no caching (local runs, tests).
   */
  SEARCH_CACHE_TTL_S?: string;
  /** Public Turnstile site key (a var in wrangler.jsonc). */
  TURNSTILE_SITE_KEY: string;
  /** Turnstile secret key: `wrangler secret put TURNSTILE_SECRET --env <env>`. Never in the repo. */
  TURNSTILE_SECRET: string;
  /**
   * Extra origins allowed to send reports, comma-separated, exact match (spec §4.8 item 6), on
   * top of the Worker's own origin, which is always allowed. A var: staging adds Vite's dev
   * server. Unset adds none.
   */
  REPORT_ORIGINS?: string;
  /**
   * The kill switch (spec §4.8 item 3): "exact" turns smart search off, "maintenance" takes
   * /api/* down; anything else is normal. Set in the dashboard only, never in wrangler.jsonc,
   * whose `keep_vars: true` keeps a deploy from resetting it.
   */
  SEARCH_OVERRIDE?: string;
  /**
   * Rate-limiting bindings (spec §4.8 item 1): 60 /api/* requests and 3 reports per 60 s per
   * client IP. Optional: without them nothing is limited (tests, local runs).
   */
  RL_READ?: RateLimit;
  RL_REPORT?: RateLimit;
  /**
   * Uncached smart searches allowed per UTC day before smart search runs keyword-only (spec
   * §4.8 item 2). Unset or not a positive integer: 20,000. A dashboard override survives deploys
   * (keep_vars), so it is not declared in wrangler.jsonc.
   */
  SMART_DAILY_BUDGET?: string;
  /**
   * The ntfy server for budget alerts (default https://ntfy.sh). A secret like the topic, so
   * the maintainer's own server's address stays out of the public repo.
   */
  NTFY_URL?: string;
  /**
   * The environment's name (a var: "staging" or "production"), shown in alert titles;
   * "production" also opens robots.txt to crawlers.
   */
  WTS_ENV?: string;
  /** ntfy topic and optional access token: `wrangler secret put NTFY_TOPIC --env <env>`. */
  NTFY_TOPIC?: string;
  NTFY_TOKEN?: string;
}
