/**
 * The Worker's bindings, as declared per environment in wrangler.jsonc.
 *
 * Runtime types (D1Database, Ai, ...) come from worker-configuration.d.ts, generated by
 * `npm run types`. This interface is written by hand rather than generated: the top-level
 * wrangler config only has DB (local/test), but every deployed environment has all of these.
 */
export interface Env {
  DB: D1Database;
  /**
   * Vectorize index (`wts-chunks-<env>`). Typed `Vectorize`, the current (v2) binding, which
   * has metadata filtering and async mutations. `VectorizeIndex` is the deprecated beta type.
   */
  VEC: Vectorize;
  AI: Ai;
  /**
   * Analytics Engine (Task 15). Optional: staging has no binding until Task 15 (wrangler.jsonc),
   * and a missing or failing analytics write must never break a search.
   */
  ANALYTICS?: AnalyticsEngineDataset;
  /**
   * Seconds to cache search responses at the edge (a var in wrangler.jsonc, "3600" in each
   * deployed environment). Unset or not a positive integer: no caching (local runs, tests).
   */
  SEARCH_CACHE_TTL_S?: string;
  /** Public Turnstile site key (a var in wrangler.jsonc). */
  TURNSTILE_SITE_KEY: string;
  /** Turnstile secret key: `wrangler secret put TURNSTILE_SECRET --env <env>`. Never in the repo. */
  TURNSTILE_SECRET: string;
}
