/**
 * The Worker's bindings, as declared per environment in wrangler.jsonc.
 *
 * Runtime types (D1Database, Ai, ...) come from worker-configuration.d.ts, generated by
 * `npm run types`. This interface is written by hand rather than generated: the top-level
 * wrangler config only has DB (local/test), but every deployed environment has all of these.
 */
export interface Env {
  DB: D1Database;
  /**
   * Vectorize index (`wts-chunks-<env>`). Typed `Vectorize`, the current (v2) binding, which
   * has metadata filtering and async mutations. `VectorizeIndex` is the deprecated beta type.
   */
  VEC: Vectorize;
  AI: Ai;
  /**
   * Analytics Engine (analytics.ts). Optional: a deploy once failed with code 10089 while it
   * was declared (Checkpoint F), and a missing or failing analytics write must never break a
   * request.
   */
  ANALYTICS?: AnalyticsEngineDataset;
  /**
   * Seconds to cache search responses at the edge (a var in wrangler.jsonc, "3600" in each
   * deployed environment). Unset or not a positive integer: no caching (local runs, tests).
   */
  SEARCH_CACHE_TTL_S?: string;
  /** Public Turnstile site key (a var in wrangler.jsonc). */
  TURNSTILE_SITE_KEY: string;
  /** Turnstile secret key: `wrangler secret put TURNSTILE_SECRET --env <env>`. Never in the repo. */
  TURNSTILE_SECRET: string;
  /**
   * Origins allowed to send reports, comma-separated, exact match (spec §4.8 item 6). A var:
   * staging allows Vite's dev server until plan 3's site exists. Unset refuses every report.
   */
  REPORT_ORIGINS?: string;
  /**
   * The kill switch (spec §4.8 item 3): "exact" turns smart search off, "maintenance" takes
   * /api/* down; anything else is normal. Set in the dashboard only, never in wrangler.jsonc,
   * whose `keep_vars: true` keeps a deploy from resetting it.
   */
  SEARCH_OVERRIDE?: string;
  /**
   * Rate-limiting bindings (spec §4.8 item 1): 60 /api/* requests and 3 reports per 60 s per
   * client IP. Optional: without them nothing is limited (tests, local runs).
   */
  RL_READ?: RateLimit;
  RL_REPORT?: RateLimit;
}
